package model.pojo;
// Generated 22/11/2019 18:35:58 by Hibernate Tools 4.3.1



/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer idDepartamento;
     private String departamento;
     private int idLocalidad;

    public Departamentos() {
    }

    public Departamentos(String departamento, int idLocalidad) {
       this.departamento = departamento;
       this.idLocalidad = idLocalidad;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public int getIdLocalidad() {
        return this.idLocalidad;
    }
    
    public void setIdLocalidad(int idLocalidad) {
        this.idLocalidad = idLocalidad;
    }




}


