package model.pojo;
// Generated 21/11/2019 19:32:45 by Hibernate Tools 4.3.1



/**
 * Localidades generated by hbm2java
 */
public class Localidades  implements java.io.Serializable {


     private Integer idLocalidad;
     private String localidad;

    public Localidades() {
    }

    public Localidades(String localidad) {
       this.localidad = localidad;
    }
   
    public Integer getIdLocalidad() {
        return this.idLocalidad;
    }
    
    public void setIdLocalidad(Integer idLocalidad) {
        this.idLocalidad = idLocalidad;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }




}


